# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom.scss variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# meta
title: Sheffield Hackspace
description: Sheffield Hackspace

# URLs
## the subpath of your site, e.g. /blog
baseurl: ""
## the base hostname & protocol for your site, e.g. http://example.com
url: "https://www.sheffieldhackspace.org.uk"
logo: /assets/images/logo.svg
rss_feed: /feed.xml
goat_counter_url: "https://sheffieldhackspacewebsite.goatcounter.com"

# socials
email: trustees@sheffieldhackspace.org.uk
twitter_username: "@shhmakers"
github_username:  "sheffieldhackspace"
facebook_username: "SHHMakers"
instagram_username: "SHHMakers"

# information - mainly used in spaceapi.json
address: "Sheffield Hackspace, Portland Works, Randall St, Highfield, Sheffield S2 4SJ"
latitude: 53.369933
longitude: -1.473812
timezone: "Europe/London"

# membership
membership_plans:
  - name: Normal membership
    value: 6
    currency: GBP
    billing_interval: monthly
    description: regularly attend any of the several open evenings a week
  - name: Keyholder membership
    value: 21
    currency: GBP
    billing_interval: monthly
    description: come and go as you please

# Build settings
theme: jekyll-theme-basically-basic

plugins:
  - jekyll-feed
  - jekyll-maps
  - jekyll-paginate

paginate: 5  # amount of posts to show per page
paginate_path: /page:num/

include:
  - _pages
  - assets

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
